@IsTest
public class FeedTriggerHandlerTest {
    
    @IsTest Private Static Void CreateFeedComment(){
        // string CommentId;
        //         User Owner = TestUtilities.internaladminuser();
        //         User Requestor = TestUtilities.internaladminuser();
       
        //        Case NewCase = New Case();
        //        newcase.RecordTypeId = '01258000000AXaXAAW';
        //        newcase.Subject = 'Test New Case';
        //        newcase.Description = 'Test Description';
        //        newcase.Status = 'Open';
        //        //newcase.Business_Impact__c = 'Change or Data Request';
        //        newcase.Business_Function__c = 'CFL';
        //        newcase.Requested_By__c = Requestor.id;
        //        newcase.OwnerId = Owner.id;
         
        // system.runAs(Requestor){
        // insert NewCase;    
          
            
        // }
        
        // System.runAs(Owner){
        //  FeedItem NewComment = New FeedItem();
        //  NewComment.Body = 'Hi and thanks for your case What Color is your hair?';
        //  NewComment.ParentId = NewCase.id;
            
        //  Insert NewComment;
            
        //     NewComment.Body = 'Hi and thanks for your case What Color is your hair? Please';
                
        //         update NewComment;
            
        //      CommentId = NewComment.Id; 
            
        //     NewCase.Status = 'Pending';
            
        //     Update NewCase;
            
        // }
        
        // System.runAs(Requestor){
        //  FeedComment NewCommentreply = New FeedComment();
        //  NewCommentreply.CommentBody = 'It Is Blue';
        //  NewCommentreply.FeedItemId = CommentId;
            
        //     insert NewCommentReply;

        //     newcommentReply.CommentBody = 'Sorry i mean red';
            
        //     update NewCommentReply;
            
        // }
        

}
    
}